[package]
name = "util-parser"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.37"
syn = { version = "2.0.79", features = ["parsing", "full", "extra-traits"] }
util-cases = { path = "../util-cases" }
